// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://openapi.json` | (string & {});
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ProjectCreateDTO
 */
export type ProjectCreateDto = {
    /**
     * Title
     */
    title: string;
    /**
     * Deadline
     */
    deadline?: string | null;
};

/**
 * ProjectResponseDTO
 */
export type ProjectResponseDto = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Deadline
     */
    deadline?: string | null;
    /**
     * Completed
     */
    completed: boolean;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ProjectUpdateDTO
 */
export type ProjectUpdateDto = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Deadline
     */
    deadline?: string | null;
};

/**
 * TaskCreateDTO
 */
export type TaskCreateDto = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Deadline
     */
    deadline?: string | null;
    /**
     * Project Id
     */
    project_id?: string | null;
};

/**
 * TaskResponseDTO
 */
export type TaskResponseDto = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Deadline
     */
    deadline?: string | null;
    /**
     * Completed
     */
    completed: boolean;
    /**
     * Project Id
     */
    project_id?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * TaskUpdateDTO
 */
export type TaskUpdateDto = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Deadline
     */
    deadline?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type GetAllTasksTasksGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tasks/';
};

export type GetAllTasksTasksGetResponses = {
    /**
     * Response Get All Tasks Tasks  Get
     *
     * Successful Response
     */
    200: Array<TaskResponseDto>;
};

export type GetAllTasksTasksGetResponse = GetAllTasksTasksGetResponses[keyof GetAllTasksTasksGetResponses];

export type CreateTaskTasksPostData = {
    body: TaskCreateDto;
    path?: never;
    query?: never;
    url: '/tasks/';
};

export type CreateTaskTasksPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTaskTasksPostError = CreateTaskTasksPostErrors[keyof CreateTaskTasksPostErrors];

export type CreateTaskTasksPostResponses = {
    /**
     * Successful Response
     */
    201: TaskResponseDto;
};

export type CreateTaskTasksPostResponse = CreateTaskTasksPostResponses[keyof CreateTaskTasksPostResponses];

export type DeleteTaskTasksTaskIdDeleteData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/tasks/{task_id}';
};

export type DeleteTaskTasksTaskIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteTaskTasksTaskIdDeleteError = DeleteTaskTasksTaskIdDeleteErrors[keyof DeleteTaskTasksTaskIdDeleteErrors];

export type DeleteTaskTasksTaskIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteTaskTasksTaskIdDeleteResponse = DeleteTaskTasksTaskIdDeleteResponses[keyof DeleteTaskTasksTaskIdDeleteResponses];

export type GetTaskTasksTaskIdGetData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/tasks/{task_id}';
};

export type GetTaskTasksTaskIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTaskTasksTaskIdGetError = GetTaskTasksTaskIdGetErrors[keyof GetTaskTasksTaskIdGetErrors];

export type GetTaskTasksTaskIdGetResponses = {
    /**
     * Successful Response
     */
    200: TaskResponseDto;
};

export type GetTaskTasksTaskIdGetResponse = GetTaskTasksTaskIdGetResponses[keyof GetTaskTasksTaskIdGetResponses];

export type UpdateTaskTasksTaskIdPutData = {
    body: TaskUpdateDto;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/tasks/{task_id}';
};

export type UpdateTaskTasksTaskIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateTaskTasksTaskIdPutError = UpdateTaskTasksTaskIdPutErrors[keyof UpdateTaskTasksTaskIdPutErrors];

export type UpdateTaskTasksTaskIdPutResponses = {
    /**
     * Successful Response
     */
    200: TaskResponseDto;
};

export type UpdateTaskTasksTaskIdPutResponse = UpdateTaskTasksTaskIdPutResponses[keyof UpdateTaskTasksTaskIdPutResponses];

export type CompleteTaskTasksTaskIdCompletePatchData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/tasks/{task_id}/complete';
};

export type CompleteTaskTasksTaskIdCompletePatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CompleteTaskTasksTaskIdCompletePatchError = CompleteTaskTasksTaskIdCompletePatchErrors[keyof CompleteTaskTasksTaskIdCompletePatchErrors];

export type CompleteTaskTasksTaskIdCompletePatchResponses = {
    /**
     * Successful Response
     */
    200: TaskResponseDto;
};

export type CompleteTaskTasksTaskIdCompletePatchResponse = CompleteTaskTasksTaskIdCompletePatchResponses[keyof CompleteTaskTasksTaskIdCompletePatchResponses];

export type GetAllProjectsProjectsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/projects/';
};

export type GetAllProjectsProjectsGetResponses = {
    /**
     * Response Get All Projects Projects  Get
     *
     * Successful Response
     */
    200: Array<ProjectResponseDto>;
};

export type GetAllProjectsProjectsGetResponse = GetAllProjectsProjectsGetResponses[keyof GetAllProjectsProjectsGetResponses];

export type CreateProjectProjectsPostData = {
    body: ProjectCreateDto;
    path?: never;
    query?: never;
    url: '/projects/';
};

export type CreateProjectProjectsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateProjectProjectsPostError = CreateProjectProjectsPostErrors[keyof CreateProjectProjectsPostErrors];

export type CreateProjectProjectsPostResponses = {
    /**
     * Successful Response
     */
    201: ProjectResponseDto;
};

export type CreateProjectProjectsPostResponse = CreateProjectProjectsPostResponses[keyof CreateProjectProjectsPostResponses];

export type DeleteProjectProjectsProjectIdDeleteData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/projects/{project_id}';
};

export type DeleteProjectProjectsProjectIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteProjectProjectsProjectIdDeleteError = DeleteProjectProjectsProjectIdDeleteErrors[keyof DeleteProjectProjectsProjectIdDeleteErrors];

export type DeleteProjectProjectsProjectIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteProjectProjectsProjectIdDeleteResponse = DeleteProjectProjectsProjectIdDeleteResponses[keyof DeleteProjectProjectsProjectIdDeleteResponses];

export type GetProjectProjectsProjectIdGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/projects/{project_id}';
};

export type GetProjectProjectsProjectIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetProjectProjectsProjectIdGetError = GetProjectProjectsProjectIdGetErrors[keyof GetProjectProjectsProjectIdGetErrors];

export type GetProjectProjectsProjectIdGetResponses = {
    /**
     * Successful Response
     */
    200: ProjectResponseDto;
};

export type GetProjectProjectsProjectIdGetResponse = GetProjectProjectsProjectIdGetResponses[keyof GetProjectProjectsProjectIdGetResponses];

export type UpdateProjectProjectsProjectIdPutData = {
    body: ProjectUpdateDto;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/projects/{project_id}';
};

export type UpdateProjectProjectsProjectIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateProjectProjectsProjectIdPutError = UpdateProjectProjectsProjectIdPutErrors[keyof UpdateProjectProjectsProjectIdPutErrors];

export type UpdateProjectProjectsProjectIdPutResponses = {
    /**
     * Successful Response
     */
    200: ProjectResponseDto;
};

export type UpdateProjectProjectsProjectIdPutResponse = UpdateProjectProjectsProjectIdPutResponses[keyof UpdateProjectProjectsProjectIdPutResponses];

export type GetProjectTasksProjectsProjectIdTasksGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/projects/{project_id}/tasks';
};

export type GetProjectTasksProjectsProjectIdTasksGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetProjectTasksProjectsProjectIdTasksGetError = GetProjectTasksProjectsProjectIdTasksGetErrors[keyof GetProjectTasksProjectsProjectIdTasksGetErrors];

export type GetProjectTasksProjectsProjectIdTasksGetResponses = {
    /**
     * Response Get Project Tasks Projects  Project Id  Tasks Get
     *
     * Successful Response
     */
    200: Array<TaskResponseDto>;
};

export type GetProjectTasksProjectsProjectIdTasksGetResponse = GetProjectTasksProjectsProjectIdTasksGetResponses[keyof GetProjectTasksProjectsProjectIdTasksGetResponses];

export type LinkTaskToProjectProjectsProjectIdTasksTaskIdLinkPostData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/projects/{project_id}/tasks/{task_id}/link';
};

export type LinkTaskToProjectProjectsProjectIdTasksTaskIdLinkPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LinkTaskToProjectProjectsProjectIdTasksTaskIdLinkPostError = LinkTaskToProjectProjectsProjectIdTasksTaskIdLinkPostErrors[keyof LinkTaskToProjectProjectsProjectIdTasksTaskIdLinkPostErrors];

export type LinkTaskToProjectProjectsProjectIdTasksTaskIdLinkPostResponses = {
    /**
     * Successful Response
     */
    200: TaskResponseDto;
};

export type LinkTaskToProjectProjectsProjectIdTasksTaskIdLinkPostResponse = LinkTaskToProjectProjectsProjectIdTasksTaskIdLinkPostResponses[keyof LinkTaskToProjectProjectsProjectIdTasksTaskIdLinkPostResponses];

export type UnlinkTaskFromProjectProjectsProjectIdTasksTaskIdUnlinkDeleteData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/projects/{project_id}/tasks/{task_id}/unlink';
};

export type UnlinkTaskFromProjectProjectsProjectIdTasksTaskIdUnlinkDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UnlinkTaskFromProjectProjectsProjectIdTasksTaskIdUnlinkDeleteError = UnlinkTaskFromProjectProjectsProjectIdTasksTaskIdUnlinkDeleteErrors[keyof UnlinkTaskFromProjectProjectsProjectIdTasksTaskIdUnlinkDeleteErrors];

export type UnlinkTaskFromProjectProjectsProjectIdTasksTaskIdUnlinkDeleteResponses = {
    /**
     * Successful Response
     */
    200: TaskResponseDto;
};

export type UnlinkTaskFromProjectProjectsProjectIdTasksTaskIdUnlinkDeleteResponse = UnlinkTaskFromProjectProjectsProjectIdTasksTaskIdUnlinkDeleteResponses[keyof UnlinkTaskFromProjectProjectsProjectIdTasksTaskIdUnlinkDeleteResponses];

export type CompleteProjectProjectsProjectIdCompletePatchData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/projects/{project_id}/complete';
};

export type CompleteProjectProjectsProjectIdCompletePatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CompleteProjectProjectsProjectIdCompletePatchError = CompleteProjectProjectsProjectIdCompletePatchErrors[keyof CompleteProjectProjectsProjectIdCompletePatchErrors];

export type CompleteProjectProjectsProjectIdCompletePatchResponses = {
    /**
     * Successful Response
     */
    200: ProjectResponseDto;
};

export type CompleteProjectProjectsProjectIdCompletePatchResponse = CompleteProjectProjectsProjectIdCompletePatchResponses[keyof CompleteProjectProjectsProjectIdCompletePatchResponses];

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
